### ISSUE TITLE
Newer version do not compatible with `pact-broker`

### ISSUE THREAD

**Issue by DKorytkin** [pact-foundation/pact-ruby-cli#90] opened 2023-01-31 08:52 UTC
I experience error when running the command `can I deploy`
```
docker run --rm -w ${pwd} -v ${pwd}:${pwd} pactfoundation/pact-cli:latest \
  pact-broker can-i-deploy  --pacticipant=Client --version=0.2.8.dev15 
```

Client version is`0.2.8.dev15`
```ruby
Error retrieving matrix. NoMethodError - undefined method `[]' for nil:NilClass
/usr/lib/ruby/gems/3.0.0/gems/pact_broker-client-1.66.0/lib/pact_broker/client/matrix/resource.rb:54:in `deployable?'
/usr/lib/ruby/gems/3.0.0/gems/pact_broker-client-1.66.0/lib/pact_broker/client/can_i_deploy.rb:44:in `create_result'
/usr/lib/ruby/gems/3.0.0/gems/pact_broker-client-1.66.0/lib/pact_broker/client/can_i_deploy.rb:34:in `call'
/usr/lib/ruby/gems/3.0.0/gems/pact_broker-client-1.66.0/lib/pact_broker/client/can_i_deploy.rb:23:in `call'
/usr/lib/ruby/gems/3.0.0/gems/pact_broker-client-1.66.0/lib/pact_broker/client/cli/matrix_commands.rb:36:in `can_i_deploy'
/usr/lib/ruby/gems/3.0.0/gems/thor-1.2.1/lib/thor/command.rb:27:in `run'
/usr/lib/ruby/gems/3.0.0/gems/thor-1.2.1/lib/thor/invocation.rb:127:in `invoke_command'
/usr/lib/ruby/gems/3.0.0/gems/thor-1.2.1/lib/thor.rb:392:in `dispatch'
/usr/lib/ruby/gems/3.0.0/gems/thor-1.2.1/lib/thor/base.rb:485:in `start'
/usr/lib/ruby/gems/3.0.0/gems/pact_broker-client-1.66.0/lib/pact_broker/client/cli/custom_thor.rb:23:in `start'
/usr/lib/ruby/gems/3.0.0/gems/pact_broker-client-1.66.0/bin/pact-broker:10:in `<top (required)>'
/usr/bin/pact-broker:25:in `load'
/usr/bin/pact-broker:25:in `<main>'
```

So problem reproduces on version:
- `pactfoundation/pact-cli:latest`
- `pactfoundation/pact-cli:0.51.0.0`

**Works fine on version:**
`pactfoundation/pact-cli:0.50.0.32`

I assume the root cause in `pact_broker-client-1.66.0` where could made incompatible changes
Odd thing is that the contract was published **OK** `Pact successfully published for Client version 0.2.8.dev15 ...`

**Comment by bethesque** [comment] 2023-02-08 23:11
Can you check if your base URL has a trailing slash on it please.

**Comment by bethesque** [comment] 2023-03-21 00:46
Please remove the trailing slash.

**Comment by YOU54F** [comment] 2023-04-26 15:51
@DKorytkin please comment if this is still an issue and we can reopen

**Comment by DKorytkin** [comment] 2023-05-12 13:54
removing `/` at the end of the URL helped.
I mean, would be nice if the client handles cases like this. (it worked before `pact-cli:0.51.0.0`)

**Comment by YOU54F** [comment] 2023-05-12 16:05
I believe this PR will solve it for all commands

https://github.com/pact-foundation/pact_broker-client/pull/132

Will keep you posted @DKorytkin

**Comment by YOU54F** [comment] 2023-05-12 16:06
>I mean, would be nice if the client handles cases like this.

I would agree :) anything we can do, to either aid the user, or at least give them hints on where things have gone wrong will only be beneficial

**Comment by YOU54F** [comment] 2023-05-12 16:06
Also thank you for the root cause investigation back to a particular version, that is incredibly helpful

**Comment by YOU54F** [comment] 2023-05-17 19:40
Should be fixed now in the latest version, see comment here in the related pull request (with thanks to a community contributor)

https://github.com/pact-foundation/pact_broker-client/pull/132#issuecomment-1551950963

**Closed** 2023-05-18 21:25 UTC
Labels: smartbear-supported
